POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpbmdvQGdvb2dsZS5jb20iLCJleHAiOjE3MjEwNzQ0NDUsInVzZXJJZCI6Mn0.TpK7Ha4xIXFiVF9nHRvhtZlwKaRi_omkEVUWDhghG-c
